# Generated by Django 2.0 on 2017-12-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employee',
        ),
    ]
